# Generated by Django 3.1.1 on 2020-09-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=512)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
    ]
